FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
COPY apps/server/package*.json ./apps/server/
COPY packages/shared/package*.json ./packages/shared/

RUN npm install

COPY apps/server ./apps/server
COPY packages/shared ./packages/shared

EXPOSE 4000
CMD ["npm", "--workspace=apps/server", "run", "dev"]
