import { db } from './db';
import type {
  Company,
  LedgerGroup,
  Ledger,
  Voucher,
  StockGroup,
  StockItem,
  Godown,
  UnitOfMeasure,
  Employee,
  SalaryStructure,
  BankAccount,
} from '@newbal/shared';

export async function checkAndSeedInitialData(): Promise<Company> {
  const existingCompanies = await db.companies.toArray();
  if (existingCompanies.length > 0) {
    return existingCompanies[0];
  }

  const companyId = 'comp-apex-01';
  const company: Company = {
    id: companyId,
    name: 'Apex Innovations Pvt. Ltd.',
    tradeName: 'Apex Technologies',
    gstin: '27AABCA1234F1Z5',
    pan: 'AABCA1234F',
    email: 'accounts@apexinnovations.in',
    phone: '+91 98200 12345',
    address: 'Plot 42, Tech Park, Andheri East, Mumbai',
    state: 'Maharashtra',
    stateCode: '27',
    pincode: '400069',
    financialYearStart: '2024-04-01',
    booksBeginningFrom: '2024-04-01',
    currencySymbol: '₹',
    currencyCode: 'INR',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  await db.companies.add(company);

  // 1. Standard Accounting Groups (Tally Standard 28 Groups)
  const primaryGroups: LedgerGroup[] = [
    { id: 'grp-capital', companyId, name: 'Capital Account', category: 'EQUITY', isPrimary: true },
    { id: 'grp-current-assets', companyId, name: 'Current Assets', category: 'ASSET', isPrimary: true },
    { id: 'grp-fixed-assets', companyId, name: 'Fixed Assets', category: 'ASSET', isPrimary: true },
    { id: 'grp-current-liab', companyId, name: 'Current Liabilities', category: 'LIABILITY', isPrimary: true },
    { id: 'grp-loans-liab', companyId, name: 'Loans (Liability)', category: 'LIABILITY', isPrimary: true },
    { id: 'grp-sales-acc', companyId, name: 'Sales Accounts', category: 'INCOME', isPrimary: true, affectsGrossProfit: true },
    { id: 'grp-purchase-acc', companyId, name: 'Purchase Accounts', category: 'EXPENSE', isPrimary: true, affectsGrossProfit: true },
    { id: 'grp-direct-income', companyId, name: 'Direct Incomes', category: 'INCOME', isPrimary: true, affectsGrossProfit: true },
    { id: 'grp-direct-expense', companyId, name: 'Direct Expenses', category: 'EXPENSE', isPrimary: true, affectsGrossProfit: true },
    { id: 'grp-indirect-income', companyId, name: 'Indirect Incomes', category: 'INCOME', isPrimary: true, affectsGrossProfit: false },
    { id: 'grp-indirect-expense', companyId, name: 'Indirect Expenses', category: 'EXPENSE', isPrimary: true, affectsGrossProfit: false },
  ];

  const subGroups: LedgerGroup[] = [
    { id: 'grp-bank-accounts', companyId, name: 'Bank Accounts', parentGroupId: 'grp-current-assets', category: 'ASSET', isPrimary: false },
    { id: 'grp-cash-in-hand', companyId, name: 'Cash-in-hand', parentGroupId: 'grp-current-assets', category: 'ASSET', isPrimary: false },
    { id: 'grp-sundry-debtors', companyId, name: 'Sundry Debtors', parentGroupId: 'grp-current-assets', category: 'ASSET', isPrimary: false },
    { id: 'grp-stock-in-hand', companyId, name: 'Stock-in-hand', parentGroupId: 'grp-current-assets', category: 'ASSET', isPrimary: false },
    { id: 'grp-sundry-creditors', companyId, name: 'Sundry Creditors', parentGroupId: 'grp-current-liab', category: 'LIABILITY', isPrimary: false },
    { id: 'grp-duties-taxes', companyId, name: 'Duties & Taxes', parentGroupId: 'grp-current-liab', category: 'LIABILITY', isPrimary: false },
    { id: 'grp-provisions', companyId, name: 'Provisions', parentGroupId: 'grp-current-liab', category: 'LIABILITY', isPrimary: false },
  ];

  await db.ledgerGroups.bulkAdd([...primaryGroups, ...subGroups]);

  // 2. Standard Ledgers
  const ledgers: Ledger[] = [
    {
      id: 'led-cash',
      companyId,
      name: 'Cash A/c',
      groupId: 'grp-cash-in-hand',
      category: 'ASSET',
      openingBalance: 45000,
      openingBalanceType: 'DR',
      isBankOrCash: true,
    },
    {
      id: 'led-sbi-bank',
      companyId,
      name: 'State Bank of India (Current A/c)',
      groupId: 'grp-bank-accounts',
      category: 'ASSET',
      openingBalance: 520000,
      openingBalanceType: 'DR',
      isBankOrCash: true,
      bankAccountNumber: '38192847192',
      bankIfsc: 'SBIN0001234',
      bankName: 'State Bank of India',
    },
    {
      id: 'led-hdfc-bank',
      companyId,
      name: 'HDFC Bank Ltd',
      groupId: 'grp-bank-accounts',
      category: 'ASSET',
      openingBalance: 240000,
      openingBalanceType: 'DR',
      isBankOrCash: true,
      bankAccountNumber: '5020001928374',
      bankIfsc: 'HDFC0000123',
      bankName: 'HDFC Bank',
    },
    {
      id: 'led-capital',
      companyId,
      name: 'Founder Capital A/c',
      groupId: 'grp-capital',
      category: 'EQUITY',
      openingBalance: 805000,
      openingBalanceType: 'CR',
    },
    {
      id: 'led-sales-dom',
      companyId,
      name: 'Domestic Sales (GST 18%)',
      groupId: 'grp-sales-acc',
      category: 'INCOME',
      openingBalance: 0,
      openingBalanceType: 'CR',
    },
    {
      id: 'led-purchase-dom',
      companyId,
      name: 'Local Purchases (GST 18%)',
      groupId: 'grp-purchase-acc',
      category: 'EXPENSE',
      openingBalance: 0,
      openingBalanceType: 'DR',
    },
    // Duties & Taxes
    {
      id: 'led-cgst-out',
      companyId,
      name: 'Output CGST @ 9%',
      groupId: 'grp-duties-taxes',
      category: 'LIABILITY',
      openingBalance: 0,
      openingBalanceType: 'CR',
    },
    {
      id: 'led-sgst-out',
      companyId,
      name: 'Output SGST @ 9%',
      groupId: 'grp-duties-taxes',
      category: 'LIABILITY',
      openingBalance: 0,
      openingBalanceType: 'CR',
    },
    {
      id: 'led-igst-out',
      companyId,
      name: 'Output IGST @ 18%',
      groupId: 'grp-duties-taxes',
      category: 'LIABILITY',
      openingBalance: 0,
      openingBalanceType: 'CR',
    },
    {
      id: 'led-cgst-in',
      companyId,
      name: 'Input CGST @ 9%',
      groupId: 'grp-duties-taxes',
      category: 'ASSET',
      openingBalance: 0,
      openingBalanceType: 'DR',
    },
    {
      id: 'led-sgst-in',
      companyId,
      name: 'Input SGST @ 9%',
      groupId: 'grp-duties-taxes',
      category: 'ASSET',
      openingBalance: 0,
      openingBalanceType: 'DR',
    },
    // Parties: Sundry Debtors
    {
      id: 'led-debtor-acme',
      companyId,
      name: 'Acme Systems Pvt Ltd',
      groupId: 'grp-sundry-debtors',
      category: 'ASSET',
      openingBalance: 120000,
      openingBalanceType: 'DR',
      gstin: '27AABCA9999F1Z1',
      state: 'Maharashtra',
      stateCode: '27',
      creditPeriodDays: 30,
      creditLimit: 500000,
      email: 'finance@acmesystems.com',
    },
    {
      id: 'led-debtor-nexgen',
      companyId,
      name: 'NexGen Digital Solutions',
      groupId: 'grp-sundry-debtors',
      category: 'ASSET',
      openingBalance: 45000,
      openingBalanceType: 'DR',
      gstin: '29AAACH8888D1Z8',
      state: 'Karnataka',
      stateCode: '29',
      creditPeriodDays: 15,
      creditLimit: 300000,
      email: 'orders@nexgen.in',
    },
    // Parties: Sundry Creditors
    {
      id: 'led-creditor-global',
      companyId,
      name: 'Global Micro Components Ltd',
      groupId: 'grp-sundry-creditors',
      category: 'LIABILITY',
      openingBalance: 85000,
      openingBalanceType: 'CR',
      gstin: '27AABCG5555L1Z4',
      state: 'Maharashtra',
      stateCode: '27',
      creditPeriodDays: 45,
      email: 'vendor@globalmicro.com',
    },
    // Expenses
    {
      id: 'led-office-rent',
      companyId,
      name: 'Office & Facility Rent',
      groupId: 'grp-indirect-expense',
      category: 'EXPENSE',
      openingBalance: 0,
      openingBalanceType: 'DR',
    },
    {
      id: 'led-salaries',
      companyId,
      name: 'Salaries and Employee Benefits',
      groupId: 'grp-indirect-expense',
      category: 'EXPENSE',
      openingBalance: 0,
      openingBalanceType: 'DR',
    },
    {
      id: 'led-electricity',
      companyId,
      name: 'Electricity & Utilities',
      groupId: 'grp-indirect-expense',
      category: 'EXPENSE',
      openingBalance: 0,
      openingBalanceType: 'DR',
    },
  ];

  await db.ledgers.bulkAdd(ledgers);

  // 3. Units of Measure & Godowns
  const units: UnitOfMeasure[] = [
    { id: 'uom-pcs', symbol: 'PCS', formalName: 'Pieces', decimalPlaces: 0 },
    { id: 'uom-box', symbol: 'BOX', formalName: 'Box (10 Pcs)', decimalPlaces: 0 },
    { id: 'uom-kgs', symbol: 'KGS', formalName: 'Kilograms', decimalPlaces: 2 },
  ];
  await db.unitsOfMeasure.bulkAdd(units);

  const godowns: Godown[] = [
    { id: 'gdn-main', companyId, name: 'Main Plant Warehouse', address: 'Floor 1, Apex Tech Park', isDefault: true },
    { id: 'gdn-branch', companyId, name: 'Navi Mumbai Distribution Center', address: 'Turbhe MIDC, Navi Mumbai' },
  ];
  await db.godowns.bulkAdd(godowns);

  // 4. Stock Groups & Items
  const stockGroups: StockGroup[] = [
    { id: 'stk-grp-electronics', companyId, name: 'Finished Electronic Devices' },
    { id: 'stk-grp-components', companyId, name: 'Raw Components & Sub-assemblies' },
  ];
  await db.stockGroups.bulkAdd(stockGroups);

  const stockItems: StockItem[] = [
    {
      id: 'itm-smart-controller',
      companyId,
      name: 'Smart IoT Controller X1',
      groupId: 'stk-grp-electronics',
      unit: 'PCS',
      hsnCode: '85371000',
      gstRate: 18,
      openingQuantity: 150,
      openingRate: 3200,
      openingValue: 480000,
      closingQuantity: 150,
      closingRate: 3200,
      closingValue: 480000,
      standardPurchaseRate: 3200,
      standardSalesRate: 4800,
      reorderLevel: 25,
      valuationMethod: 'FIFO',
      batchTrackingEnabled: true,
    },
    {
      id: 'itm-sensor-module',
      companyId,
      name: 'Industrial Precision Sensor V2',
      groupId: 'stk-grp-components',
      unit: 'PCS',
      hsnCode: '90318000',
      gstRate: 18,
      openingQuantity: 500,
      openingRate: 650,
      openingValue: 325000,
      closingQuantity: 500,
      closingRate: 650,
      closingValue: 325000,
      standardPurchaseRate: 650,
      standardSalesRate: 1100,
      reorderLevel: 100,
      valuationMethod: 'FIFO',
    },
    {
      id: 'itm-power-supply',
      companyId,
      name: '24V Industrial Power Supply Unit',
      groupId: 'stk-grp-components',
      unit: 'PCS',
      hsnCode: '85044090',
      gstRate: 18,
      openingQuantity: 200,
      openingRate: 950,
      openingValue: 190000,
      closingQuantity: 200,
      closingRate: 950,
      closingValue: 190000,
      standardPurchaseRate: 950,
      standardSalesRate: 1500,
      reorderLevel: 40,
      valuationMethod: 'FIFO',
    },
  ];
  await db.stockItems.bulkAdd(stockItems);

  // 5. Employees & Salary Structures
  const employees: Employee[] = [
    {
      id: 'emp-001',
      companyId,
      employeeCode: 'EMP101',
      name: 'Rahul Sharma',
      designation: 'Principal Systems Architect',
      department: 'Engineering',
      dateOfJoining: '2023-01-15',
      email: 'rahul.s@apexinnovations.in',
      phone: '+91 98111 22334',
      pan: 'ABCPS1234D',
      bankAccount: '91827364510',
      bankIfsc: 'HDFC0000123',
      bankName: 'HDFC Bank',
      uanPf: '100987654321',
      status: 'ACTIVE',
    },
    {
      id: 'emp-002',
      companyId,
      employeeCode: 'EMP102',
      name: 'Priya Patel',
      designation: 'Senior Accounts Manager',
      department: 'Finance',
      dateOfJoining: '2023-03-01',
      email: 'priya.p@apexinnovations.in',
      phone: '+91 98222 33445',
      pan: 'ABCDE5678F',
      bankAccount: '12345678901',
      bankIfsc: 'SBIN0001234',
      bankName: 'State Bank of India',
      uanPf: '100987654322',
      status: 'ACTIVE',
    },
  ];
  await db.employees.bulkAdd(employees);

  const salaryStructures: SalaryStructure[] = [
    {
      id: 'sal-001',
      employeeId: 'emp-001',
      effectiveFrom: '2024-04-01',
      basicSalary: 65000,
      hra: 26000,
      conveyanceAllowance: 5000,
      specialAllowance: 14000,
      medicalAllowance: 2000,
      pfDeductionRate: 12,
      esiDeductionRate: 0,
      professionalTax: 200,
      tdsMonthly: 4500,
    },
    {
      id: 'sal-002',
      employeeId: 'emp-002',
      effectiveFrom: '2024-04-01',
      basicSalary: 40000,
      hra: 16000,
      conveyanceAllowance: 3000,
      specialAllowance: 8000,
      medicalAllowance: 1250,
      pfDeductionRate: 12,
      esiDeductionRate: 0,
      professionalTax: 200,
      tdsMonthly: 2100,
    },
  ];
  await db.salaryStructures.bulkAdd(salaryStructures);

  // 6. Bank Accounts master
  const bankAcc: BankAccount = {
    id: 'bnk-sbi-01',
    companyId,
    ledgerId: 'led-sbi-bank',
    bankName: 'State Bank of India',
    accountNumber: '38192847192',
    ifscCode: 'SBIN0001234',
    branchName: 'Andheri East Commercial Branch',
    bookBalance: 520000,
    bankBalance: 520000,
  };
  await db.bankAccounts.add(bankAcc);

  // 7. Seed realistic Initial Vouchers (Sales, Purchase, Payment, Receipt)
  const vouchers: Voucher[] = [
    {
      id: 'vch-sales-01',
      companyId,
      voucherNumber: 'INV/24-25/001',
      voucherType: 'SALES',
      date: '2024-05-10',
      referenceNumber: 'PO-ACM-881',
      partyLedgerId: 'led-debtor-acme',
      partyName: 'Acme Systems Pvt Ltd',
      isInterstate: false,
      narration: 'Being goods sold to Acme Systems against PO-ACM-881',
      totalTaxableAmount: 48000,
      totalCgst: 4320,
      totalSgst: 4320,
      totalIgst: 0,
      grandTotal: 56640,
      entries: [
        { ledgerId: 'led-debtor-acme', ledgerName: 'Acme Systems Pvt Ltd', amount: 56640, type: 'DR' },
        { ledgerId: 'led-sales-dom', ledgerName: 'Domestic Sales (GST 18%)', amount: 48000, type: 'CR' },
        { ledgerId: 'led-cgst-out', ledgerName: 'Output CGST @ 9%', amount: 4320, type: 'CR' },
        { ledgerId: 'led-sgst-out', ledgerName: 'Output SGST @ 9%', amount: 4320, type: 'CR' },
      ],
      inventoryItems: [
        {
          stockItemId: 'itm-smart-controller',
          itemName: 'Smart IoT Controller X1',
          hsnCode: '85371000',
          godownId: 'gdn-main',
          quantity: 10,
          unit: 'PCS',
          rate: 4800,
          taxableAmount: 48000,
          gstRate: 18,
          cgstAmount: 4320,
          sgstAmount: 4320,
          igstAmount: 0,
          totalAmount: 56640,
        },
      ],
      status: 'POSTED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'vch-sales-02',
      companyId,
      voucherNumber: 'INV/24-25/002',
      voucherType: 'SALES',
      date: '2024-05-18',
      referenceNumber: 'PO-NX-402',
      partyLedgerId: 'led-debtor-nexgen',
      partyName: 'NexGen Digital Solutions',
      isInterstate: true,
      narration: 'Being interstate supply of IoT controllers to Bangalore',
      totalTaxableAmount: 96000,
      totalCgst: 0,
      totalSgst: 0,
      totalIgst: 17280,
      grandTotal: 113280,
      entries: [
        { ledgerId: 'led-debtor-nexgen', ledgerName: 'NexGen Digital Solutions', amount: 113280, type: 'DR' },
        { ledgerId: 'led-sales-dom', ledgerName: 'Domestic Sales (GST 18%)', amount: 96000, type: 'CR' },
        { ledgerId: 'led-igst-out', ledgerName: 'Output IGST @ 18%', amount: 17280, type: 'CR' },
      ],
      inventoryItems: [
        {
          stockItemId: 'itm-smart-controller',
          itemName: 'Smart IoT Controller X1',
          hsnCode: '85371000',
          godownId: 'gdn-main',
          quantity: 20,
          unit: 'PCS',
          rate: 4800,
          taxableAmount: 96000,
          gstRate: 18,
          cgstAmount: 0,
          sgstAmount: 0,
          igstAmount: 17280,
          totalAmount: 113280,
        },
      ],
      status: 'POSTED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'vch-purchase-01',
      companyId,
      voucherNumber: 'PUR/24-25/001',
      voucherType: 'PURCHASE',
      date: '2024-05-05',
      referenceNumber: 'INV-GM-9021',
      partyLedgerId: 'led-creditor-global',
      partyName: 'Global Micro Components Ltd',
      isInterstate: false,
      narration: 'Purchase of sensors and power supply units',
      totalTaxableAmount: 65000,
      totalCgst: 5850,
      totalSgst: 5850,
      totalIgst: 0,
      grandTotal: 76700,
      entries: [
        { ledgerId: 'led-purchase-dom', ledgerName: 'Local Purchases (GST 18%)', amount: 65000, type: 'DR' },
        { ledgerId: 'led-cgst-in', ledgerName: 'Input CGST @ 9%', amount: 5850, type: 'DR' },
        { ledgerId: 'led-sgst-in', ledgerName: 'Input SGST @ 9%', amount: 5850, type: 'DR' },
        { ledgerId: 'led-creditor-global', ledgerName: 'Global Micro Components Ltd', amount: 76700, type: 'CR' },
      ],
      inventoryItems: [
        {
          stockItemId: 'itm-sensor-module',
          itemName: 'Industrial Precision Sensor V2',
          hsnCode: '90318000',
          godownId: 'gdn-main',
          quantity: 100,
          unit: 'PCS',
          rate: 650,
          taxableAmount: 65000,
          gstRate: 18,
          cgstAmount: 5850,
          sgstAmount: 5850,
          igstAmount: 0,
          totalAmount: 76700,
        },
      ],
      status: 'POSTED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'vch-receipt-01',
      companyId,
      voucherNumber: 'RCT/24-25/001',
      voucherType: 'RECEIPT',
      date: '2024-05-20',
      referenceNumber: 'NEFT-891283',
      narration: 'Received payment from Acme Systems via NEFT',
      grandTotal: 50000,
      entries: [
        { ledgerId: 'led-sbi-bank', ledgerName: 'State Bank of India (Current A/c)', amount: 50000, type: 'DR' },
        { ledgerId: 'led-debtor-acme', ledgerName: 'Acme Systems Pvt Ltd', amount: 50000, type: 'CR' },
      ],
      status: 'POSTED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'vch-payment-01',
      companyId,
      voucherNumber: 'PMT/24-25/001',
      voucherType: 'PAYMENT',
      date: '2024-05-25',
      referenceNumber: 'CHQ-002194',
      narration: 'Office rent paid for May 2024',
      grandTotal: 35000,
      entries: [
        { ledgerId: 'led-office-rent', ledgerName: 'Office & Facility Rent', amount: 35000, type: 'DR' },
        { ledgerId: 'led-sbi-bank', ledgerName: 'State Bank of India (Current A/c)', amount: 35000, type: 'CR' },
      ],
      status: 'POSTED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  await db.vouchers.bulkAdd(vouchers);

  // Add initial audit log
  await db.auditLogs.add({
    id: 'log-init-01',
    companyId,
    timestamp: new Date().toISOString(),
    action: 'CREATE',
    entity: 'COMPANY',
    entityId: companyId,
    details: 'System initialized with standard chart of accounts, ledgers, items, and seed vouchers',
    user: 'Administrator',
  });

  return company;
}
